import React from 'react';
import type { IconType } from 'react-icons';
import {
  SiApplemusic,
  SiBitcoin,
  SiBluesky,
  SiBuymeacoffee,
  SiCashapp,
  SiDiscord,
  SiEthereum,
  SiFacebook,
  SiGithub,
  SiGitlab,
  SiInstagram,
  SiKick,
  SiKofi,
  SiLastdotfm,
  SiLitecoin,
  SiMonero,
  SiOnlyfans,
  SiPatreon,
  SiPaypal,
  SiPinterest,
  SiPlaystation,
  SiReddit,
  SiRoblox,
  SiSignal,
  SiSnapchat,
  SiSolana,
  SiSoundcloud,
  SiSpotify,
  SiSteam,
  SiTelegram,
  SiThreads,
  SiTiktok,
  SiTwitch,
  SiVenmo,
  SiVk,
  SiWhatsapp,
  SiX,
  SiXrp,
  SiYoutube,
} from 'react-icons/si';
import { FaLinkedin, FaXbox } from 'react-icons/fa6';
import { MdEmail, MdLanguage } from 'react-icons/md';

interface SocialIconProps {
  platform: string;
  className?: string;
}

const ICON_MAP: Record<string, IconType> = {
  discord: SiDiscord,
  github: SiGithub,
  telegram: SiTelegram,
  youtube: SiYoutube,
  steam: SiSteam,
  spotify: SiSpotify,
  twitter: SiX,
  x: SiX,
  instagram: SiInstagram,
  tiktok: SiTiktok,
  twitch: SiTwitch,
  vk: SiVk,
  reddit: SiReddit,
  snapchat: SiSnapchat,
  facebook: SiFacebook,
  linkedin: FaLinkedin,
  whatsapp: SiWhatsapp,
  email: MdEmail,
  soundcloud: SiSoundcloud,
  patreon: SiPatreon,
  kick: SiKick,
  threads: SiThreads,
  roblox: SiRoblox,
  paypal: SiPaypal,
  cashapp: SiCashapp,
  venmo: SiVenmo,
  playstation: SiPlaystation,
  xbox: FaXbox,
  applemusic: SiApplemusic,
  gitlab: SiGitlab,
  bluesky: SiBluesky,
  onlyfans: SiOnlyfans,
  pinterest: SiPinterest,
  lastfm: SiLastdotfm,
  buymeacoffee: SiBuymeacoffee,
  kofi: SiKofi,
  signal: SiSignal,
  bitcoin: SiBitcoin,
  ethereum: SiEthereum,
  litecoin: SiLitecoin,
  solana: SiSolana,
  monero: SiMonero,
  xrp: SiXrp,
  website: MdLanguage,
};

export default function SocialIcon({ platform, className = 'w-5 h-5' }: SocialIconProps) {
  const Icon = ICON_MAP[platform] || ICON_MAP.website;
  return React.createElement(Icon, { className, 'aria-hidden': true });
}
